// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkxmlmbmcekgcaoyomkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdreG1sbWJtY2VrZ2Nhb3lvbWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTQ1MDUsImV4cCI6MjA2NDY5MDUwNX0.0hPSJD8Xo3vyQcR2UCV_Cc1K760__TCOMVq76MVm1j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);